"""User Model update

Revision ID: 57c77c8a30d3
Revises: 2eeffa086a7f
Create Date: 2026-04-23 17:52:29.391479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57c77c8a30d3'
down_revision: Union[str, Sequence[str], None] = '2eeffa086a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
